import type { Products } from "./columns";

export async function getData(): Promise<Products[]> {
  // Fetch data from your API here.
  return [
    {
      id: "PRD001",
      name: "Máy cưa xăng STIHL MS180",
      slug: "may-cua-xang-stihl-ms180",
      description:
        "Máy cưa xăng STIHL MS180 phù hợp cho công việc cắt tỉa cây cối trong nông trại, công suất mạnh mẽ, thiết kế gọn nhẹ.",
      category: "Máy cưa",
      brand: "STIHL",
      price: 3200000,
      credit_price: 3500000,
      stock: 15,
      images: [
        "https://www.ketnoitieudung.vn/data/bt1/may-cua-xich-xang-stihl-ms-180.jpg",
        "https://thietbiplaza.com/netviet/filesupload/image/2019/Sthil-MS180.jpg",
      ],
      specs: [
        "Dung tích xi lanh: 31.8 cc",
        "Công suất: 1.5 kW",
        "Trọng lượng: 4.1 kg",
        "Loại xăng: Xăng pha nhớt 2 thì",
      ],
      created_at: "2024-10-15T08:30:00Z",
      is_active: true,
      is_deleted: false,
    },
    {
      id: "PRD002",
      name: "Máy cắt cỏ Honda GX35",
      slug: "may-cat-co-honda-gx35",
      description:
        "Máy cắt cỏ Honda GX35 sử dụng động cơ 4 thì mạnh mẽ, tiết kiệm nhiên liệu và dễ khởi động, phù hợp với mọi địa hình.",
      category: "Máy cắt cỏ",
      brand: "Honda",
      price: 2800000,
      credit_price: 3050000,
      stock: 25,
      images: [
        "https://example.com/images/honda-gx35-1.jpg",
        "https://example.com/images/honda-gx35-2.jpg",
      ],
      specs: [
        "Động cơ: 4 thì, 1 xi lanh",
        "Công suất: 1.6 HP",
        "Bình nhiên liệu: 0.65 lít",
        "Trọng lượng: 7.5 kg",
      ],
      created_at: "2024-11-02T10:00:00Z",
      is_active: false,
      is_deleted: false,
    },
    {
      id: "PRD003",
      name: "Máy xịt thuốc áp lực Mitsuka HL767",
      slug: "may-xit-thuoc-mitsuka-hl767",
      description:
        "Máy xịt thuốc HL767 dùng trong việc phun thuốc trừ sâu, diệt cỏ, có thể dùng rửa xe, xịt rửa chuồng trại.",
      category: "Máy xịt thuốc",
      brand: "Mitsuka",
      price: 2100000,
      credit_price: 2300000,
      stock: 10,
      images: ["https://example.com/images/mitsuka-hl767.jpg"],
      specs: [
        "Áp suất: 25 - 40 bar",
        "Công suất: 1.5 HP",
        "Dung tích bình: 25 lít",
        "Khoảng cách phun: 8 - 10 mét",
      ],
      created_at: "2025-01-05T14:45:00Z",
      is_active: true,
      is_deleted: true,
    },
    {
      id: "PRD004",
      name: "Máy bơm nước mini Kangaroo KG600",
      slug: "may-bom-nuoc-mini-kangaroo-kg600",
      description:
        "Máy bơm nước mini Kangaroo KG600 nhỏ gọn, tiện lợi cho việc tưới cây, bơm nước sinh hoạt gia đình.",
      category: "Máy bơm nước",
      brand: "Kangaroo",
      price: 850000,
      credit_price: 920000,
      stock: 40,
      images: [
        "https://example.com/images/kangaroo-kg600-1.jpg",
        "https://example.com/images/kangaroo-kg600-2.jpg",
      ],
      specs: [
        "Công suất: 300W",
        "Lưu lượng: 1.5 m³/giờ",
        "Độ cao hút: 8 mét",
        "Trọng lượng: 3.5 kg",
      ],
      created_at: "2024-09-20T09:15:00Z",
      is_active: true,
      is_deleted: false,
    },
    {
      id: "PRD005",
      name: "Máy rửa xe cao áp Karcher K2 Full Control",
      slug: "may-rua-xe-karcher-k2-full-control",
      description:
        "Máy rửa xe Karcher K2 Full Control với áp lực phun mạnh mẽ, lý tưởng để làm sạch xe cộ, sân vườn và đồ dùng gia đình.",
      category: "Máy rửa xe",
      brand: "Karcher",
      price: 4500000,
      credit_price: 4850000,
      stock: 12,
      images: [
        "https://example.com/images/karcher-k2-front.jpg",
        "https://example.com/images/karcher-k2-accessories.jpg",
      ],
      specs: [
        "Áp lực: 110 bar",
        "Lưu lượng nước: 360 lít/giờ",
        "Công suất: 1.4 kW",
        "Trọng lượng: 4.3 kg",
      ],
      created_at: "2025-02-10T11:00:00Z",
      is_active: true,
      is_deleted: false,
    },
    {
      id: "PRD006",
      name: "Máy khoan bê tông Bosch GBH 2-26 DRE",
      slug: "may-khoan-be-tong-bosch-gbh-2-26-dre",
      description:
        "Máy khoan bê tông Bosch GBH 2-26 DRE đa năng với 3 chế độ: khoan, khoan búa và đục, mạnh mẽ và bền bỉ.",
      category: "Dụng cụ điện",
      brand: "Bosch",
      price: 3800000,
      credit_price: 4100000,
      stock: 8,
      images: [
        "https://example.com/images/bosch-gbh226-1.jpg",
        "https://example.com/images/bosch-gbh226-2.jpg",
      ],
      specs: [
        "Công suất: 800W",
        "Tốc độ không tải: 0 - 900 vòng/phút",
        "Tốc độ đập: 0 - 4000 lần/phút",
        "Đường kính khoan tối đa: 26mm (bê tông)",
      ],
      created_at: "2024-12-01T15:30:00Z",
      is_active: true,
      is_deleted: false,
    },
    {
      id: "PRD007",
      name: "Máy hàn điện tử Jasic ARC 200",
      slug: "may-han-dien-tu-jasic-arc-200",
      description:
        "Máy hàn điện tử Jasic ARC 200 nhỏ gọn, dễ di chuyển, cho mối hàn đẹp, ổn định, phù hợp cho thợ cơ khí và gia đình.",
      category: "Dụng cụ điện",
      brand: "Jasic",
      price: 2500000,
      credit_price: 2750000,
      stock: 18,
      images: [
        "https://example.com/images/jasic-arc200-1.jpg",
        "https://example.com/images/jasic-arc200-2.jpg",
      ],
      specs: [
        "Điện áp vào: 220V",
        "Dòng hàn: 20 - 200A",
        "Que hàn: 1.6 - 4.0 mm",
        "Trọng lượng: 5 kg",
      ],
      created_at: "2025-03-15T09:00:00Z",
      is_active: true,
      is_deleted: false,
    },
    {
      id: "PRD008",
      name: "Máy nén khí mini Pegasus TM-25L",
      slug: "may-nen-khi-mini-pegasus-tm-25l",
      description:
        "Máy nén khí mini Pegasus TM-25L dung tích 25 lít, nhỏ gọn, ít ồn, phù hợp cho các công việc gia đình, phun sơn nhỏ.",
      category: "Máy nén khí",
      brand: "Pegasus",
      price: 1800000,
      credit_price: 1950000,
      stock: 9,
      images: [
        "https://example.com/images/pegasus-tm25l-1.jpg",
        "https://example.com/images/pegasus-tm25l-2.jpg",
      ],
      specs: [
        "Dung tích bình: 25 lít",
        "Áp suất tối đa: 8 bar",
        "Công suất: 1.5 HP",
        "Lưu lượng khí: 195 lít/phút",
      ],
      created_at: "2024-10-01T16:00:00Z",
      is_active: true,
      is_deleted: false,
    },
    {
      id: "PRD009",
      name: "Máy phát điện Hyundai HY3000",
      slug: "may-phat-dien-hyundai-hy3000",
      description:
        "Máy phát điện Hyundai HY3000 công suất 2.8kW, phù hợp cung cấp điện dự phòng cho gia đình hoặc công trường nhỏ.",
      category: "Máy phát điện",
      brand: "Hyundai",
      price: 7500000,
      credit_price: 8000000,
      stock: 5,
      images: [
        "https://example.com/images/hyundai-hy3000-1.jpg",
        "https://example.com/images/hyundai-hy3000-2.jpg",
      ],
      specs: [
        "Công suất liên tục: 2.8 kW",
        "Công suất tối đa: 3.0 kW",
        "Dung tích bình nhiên liệu: 15 lít",
        "Động cơ: 4 thì",
      ],
      created_at: "2025-01-20T13:00:00Z",
      is_active: true,
      is_deleted: false,
    },
    {
      id: "PRD010",
      name: "Máy phun sương Fujie HM-2700",
      slug: "may-phun-suong-fujie-hm-2700",
      description:
        "Máy phun sương Fujie HM-2700 tạo độ ẩm, làm mát không khí hiệu quả, phù hợp cho quán cà phê, nhà hàng, vườn ươm.",
      category: "Máy phun sương",
      brand: "Fujie",
      price: 1200000,
      credit_price: 1300000,
      stock: 20,
      images: [
        "https://example.com/images/fujie-hm2700-1.jpg",
        "https://example.com/images/fujie-hm2700-2.jpg",
      ],
      specs: [
        "Công suất: 100W",
        "Lưu lượng phun: 2.5 lít/giờ",
        "Phạm vi hoạt động: 20-30 m²",
        "Độ ồn: < 45dB",
      ],
      created_at: "2024-11-25T10:30:00Z",
      is_active: true,
      is_deleted: false,
    },
    {
      id: "PRD011",
      name: "Máy cắt gạch Makita M4101",
      slug: "may-cat-gach-makita-m4101",
      description:
        "Máy cắt gạch Makita M4101 nhỏ gọn, dễ sử dụng, cắt gạch nhanh chóng và chính xác, phù hợp cho các công trình vừa và nhỏ.",
      category: "Dụng cụ điện",
      brand: "Makita",
      price: 1500000,
      credit_price: 1650000,
      stock: 10,
      images: [
        "https://example.com/images/makita-m4101-1.jpg",
        "https://example.com/images/makita-m4101-2.jpg",
      ],
      specs: [
        "Công suất: 1200W",
        "Đường kính lưỡi: 110 mm",
        "Độ sâu cắt tối đa: 34 mm",
        "Tốc độ không tải: 13000 vòng/phút",
      ],
      created_at: "2024-09-01T11:45:00Z",
      is_active: true,
      is_deleted: false,
    },
    {
      id: "PRD012",
      name: "Máy mài góc Dewalt DWE4010",
      slug: "may-mai-goc-dewalt-dwe4010",
      description:
        "Máy mài góc Dewalt DWE4010 thiết kế nhỏ gọn, công suất mạnh mẽ, an toàn khi sử dụng cho các công việc mài, cắt kim loại.",
      category: "Dụng cụ điện",
      brand: "Dewalt",
      price: 1100000,
      credit_price: 1200000,
      stock: 22,
      images: [
        "https://example.com/images/dewalt-dwe4010-1.jpg",
        "https://example.com/images/dewalt-dwe4010-2.jpg",
      ],
      specs: [
        "Công suất: 730W",
        "Đường kính đĩa: 100 mm",
        "Tốc độ không tải: 11000 vòng/phút",
        "Trọng lượng: 1.8 kg",
      ],
      created_at: "2025-04-01T14:00:00Z",
      is_active: true,
      is_deleted: false,
    },
    {
      id: "PRD013",
      name: "Máy hàn que mini Kenko ARC-200A",
      slug: "may-han-que-mini-kenko-arc-200a",
      description:
        "Máy hàn que mini Kenko ARC-200A nhỏ gọn, dễ mang vác, phù hợp cho việc sửa chữa dân dụng, hàn sắt tại nhà.",
      category: "Dụng cụ điện",
      brand: "Kenko",
      price: 1900000,
      credit_price: 2050000,
      stock: 15,
      images: ["https://example.com/images/kenko-arc200a-1.jpg"],
      specs: [
        "Điện áp vào: 220V",
        "Dòng hàn: 10 - 200A",
        "Que hàn: 1.6 - 3.2 mm",
        "Hiệu suất: 85%",
      ],
      created_at: "2024-11-10T08:00:00Z",
      is_active: true,
      is_deleted: false,
    },
    {
      id: "PRD014",
      name: "Máy rửa xe mini Lutian LT-210G",
      slug: "may-rua-xe-mini-lutian-lt-210g",
      description:
        "Máy rửa xe mini Lutian LT-210G tiện lợi cho việc rửa xe máy, ô tô, sân vườn, có khả năng tự hút nước.",
      category: "Máy rửa xe",
      brand: "Lutian",
      price: 1600000,
      credit_price: 1750000,
      stock: 18,
      images: [
        "https://example.com/images/lutian-lt210g-1.jpg",
        "https://example.com/images/lutian-lt210g-2.jpg",
      ],
      specs: [
        "Áp lực: 80 - 120 bar",
        "Lưu lượng nước: 5.5 lít/phút",
        "Công suất: 1.5 kW",
        "Trọng lượng: 10 kg",
      ],
      created_at: "2025-03-01T16:30:00Z",
      is_active: true,
      is_deleted: false,
    },
    {
      id: "PRD015",
      name: "Máy cắt sắt Bosch GCO 220",
      slug: "may-cat-sat-bosch-gco-220",
      description:
        "Máy cắt sắt Bosch GCO 220 mạnh mẽ, cắt nhanh và chính xác các loại vật liệu kim loại, phù hợp cho công trình xây dựng.",
      category: "Dụng cụ điện",
      brand: "Bosch",
      price: 3000000,
      credit_price: 3250000,
      stock: 7,
      images: ["https://example.com/images/bosch-gco220-1.jpg"],
      specs: [
        "Công suất: 2200W",
        "Đường kính đĩa: 355 mm",
        "Tốc độ không tải: 3800 vòng/phút",
        "Khả năng cắt thép tròn: 130 mm",
      ],
      created_at: "2025-02-20T09:45:00Z",
      is_active: true,
      is_deleted: false,
    },
    {
      id: "PRD016",
      name: "Máy thổi lá Makita UB1103",
      slug: "may-thoi-la-makita-ub1103",
      description:
        "Máy thổi lá Makita UB1103 thiết kế nhẹ, gọn, dùng để thổi bụi, lá cây, làm sạch sân vườn nhanh chóng.",
      category: "Dụng cụ làm vườn",
      brand: "Makita",
      price: 950000,
      credit_price: 1050000,
      stock: 28,
      images: [
        "https://example.com/images/makita-ub1103-1.jpg",
        "https://example.com/images/makita-ub1103-2.jpg",
      ],
      specs: [
        "Công suất: 600W",
        "Lưu lượng khí: 4.1 m³/phút",
        "Trọng lượng: 2 kg",
        "Độ ồn: 85 dB",
      ],
      created_at: "2024-10-25T13:10:00Z",
      is_active: true,
      is_deleted: false,
    },
    {
      id: "PRD017",
      name: "Máy phun thuốc diệt côn trùng Mitsuka KS2020",
      slug: "may-phun-thuoc-diet-con-trung-mitsuka-ks2020",
      description:
        "Máy phun thuốc diệt côn trùng Mitsuka KS2020 hiệu quả cao, dễ sử dụng, thích hợp cho việc diệt muỗi, côn trùng trong nhà và vườn.",
      category: "Máy xịt thuốc",
      brand: "Mitsuka",
      price: 1500000,
      credit_price: 1650000,
      stock: 0,
      images: ["https://example.com/images/mitsuka-ks2020-1.jpg"],
      specs: [
        "Dung tích bình: 20 lít",
        "Loại động cơ: Xăng 2 thì",
        "Phạm vi phun: 6 - 8 mét",
        "Trọng lượng: 11 kg",
      ],
      created_at: "2025-01-10T11:00:00Z",
      is_active: true,
      is_deleted: false,
    },
    {
      id: "PRD018",
      name: "Máy chà nhám rung Bosch GSS 2300",
      slug: "may-cha-nham-rung-bosch-gss-2300",
      description:
        "Máy chà nhám rung Bosch GSS 2300 cho bề mặt mịn, hoạt động ổn định, lý tưởng cho việc hoàn thiện gỗ, kim loại.",
      category: "Dụng cụ điện",
      brand: "Bosch",
      price: 1300000,
      credit_price: 1420000,
      stock: 14,
      images: ["https://example.com/images/bosch-gss2300-1.jpg"],
      specs: [
        "Công suất: 190W",
        "Kích thước đế: 92 x 182 mm",
        "Tốc độ không tải: 12000 vòng/phút",
        "Trọng lượng: 1.6 kg",
      ],
      created_at: "2024-12-10T14:00:00Z",
      is_active: true,
      is_deleted: false,
    },
    {
      id: "PRD019",
      name: "Máy cắt cỏ đẩy tay Greenworks 25022",
      slug: "may-cat-co-day-tay-greenworks-25022",
      description:
        "Máy cắt cỏ đẩy tay Greenworks 25022 không dây, chạy pin, thân thiện môi trường, phù hợp cắt cỏ sân vườn nhỏ.",
      category: "Máy cắt cỏ",
      brand: "Greenworks",
      price: 5200000,
      credit_price: 5600000,
      stock: 6,
      images: ["https://example.com/images/greenworks-25022-1.jpg"],
      specs: [
        "Loại pin: Lithium-ion 40V",
        "Chiều rộng cắt: 40 cm",
        "Thời gian hoạt động: 45 phút",
        "Trọng lượng: 15 kg",
      ],
      created_at: "2025-04-10T10:00:00Z",
      is_active: true,
      is_deleted: false,
    },
    {
      id: "PRD020",
      name: "Máy rửa xe gia đình Hyundai HDY-PW1500",
      slug: "may-rua-xe-gia-dinh-hyundai-hdy-pw1500",
      description:
        "Máy rửa xe gia đình Hyundai HDY-PW1500 nhỏ gọn, dễ sử dụng, áp lực mạnh mẽ cho mọi nhu cầu rửa xe, vệ sinh sân vườn.",
      category: "Máy rửa xe",
      brand: "Hyundai",
      price: 2200000,
      credit_price: 2400000,
      stock: 16,
      images: [
        "https://example.com/images/hyundai-pw1500-1.jpg",
        "https://example.com/images/hyundai-pw1500-2.jpg",
      ],
      specs: [
        "Áp lực: 100 bar",
        "Công suất: 1.5 kW",
        "Lưu lượng nước: 6.5 lít/phút",
        "Trọng lượng: 8.5 kg",
      ],
      created_at: "2024-09-05T09:00:00Z",
      is_active: true,
      is_deleted: false,
    },
  ];
}
